### ISSUE TITLE
Checklist Review for v26 (protos)

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/LilyPad_Arduino_Simple#1]
1) Is proper attribution given to the original designer? [YES]
comment: the text objects for the designers and revisers and the version # should all be on the symbols layer

2) If net labels are used, are they the correct 'FLAG' type? [NO]
comment: Looks like your RXI and TXO flags (nets) on JP2 have gone missing - perhaps when you deleted test points. please reconnect/reroute

3) Are junction dots used for all 3-wire connections? [YES]
comment: un-necessary node on the 5V net (bottom left of sch)

4) Does every part have a NAME and VALUE (with proper prefix and no '$')? [NO]
comment: ATMEGA328 needs 'U1' and value

5) Is the FTDI connector oriented so the FTDI breakout can be slid on properly (IC side up, header side down)? [NO]
comment: needs nets and traces for TX RX routed/corrected

6) Is the direction of TX/RX serial connections correct? [NO]
comment: can't check yet until they are routed again

7) Does it pass SparkFun DRC? [NO]
comment: 11 errors still present but they are cool to approve

8) Is there a note for a board thickness other than 0.63 inch?  [YES]
comment: should be on tdocu layer

9) Are measurements included for outer dimension and standoffs (Eagle layer 47)? [YES]
comment: the text object "dimension in inches" should also be on layer 47

10) Are all connectors labeled with their purpose? [NO]
comment: "I2C" on both A4 and A5 is helpful, but I think that they should be labeled "SDA" and "CLK" - this is our usual labeling of I2C lines, however I nkow lilypad is never usual

**Comment by RobotGirlfriend** [comment]
1) fixed
2) added and re-routed
3) removed
4) un-delete!
5)  I think addressing #2 took care of this as well, if I'm wrong, let me know!
6) Let me know how this looks now
7) Approved
8) Fixed!
9) Moved!
10) Totally agree- in fact, they were labelled that way, and I must have failed to save the change. fixed.

**Comment by lewispg228** [comment]
All looks good. thanks!
